services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: useful-contents-library
    container_name: useful_contents_app
    ports:
      - "8080:80"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=library_db
      - DB_USERNAME=library_user
      - DB_PASSWORD=secret
  db:
    image: postgres:15
    container_name: library_db
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  nginx:
    image: nginx:latest
    container_name: library_nginx
    ports:
      - "3000:80"
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
volumes:
  pgdata: